"""empty message

Revision ID: cbb6f96c94c0
Revises: 7e69918b1933
Create Date: 2016-03-28 19:58:48.808000

"""

# revision identifiers, used by Alembic.
revision = 'cbb6f96c94c0'
down_revision = '7e69918b1933'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'password_hash')
    ### end Alembic commands ###
